title = "Stránky LARPu Erinor (pořádané skupinou Pilirion) &ndash; knihovna: Traktát o magii erinorské";
keywords = "larp, erinor, fantasy, dřevárny, roleplay, knihovna, traktát, magie";
description = "Stránky LARPu Erinor, sekce knihovna, Traktát o magii erinorské";

Sem lze napsat libovolný komentář, nebude zobrazen. Zobrazí se pouze text pod čarou.
----------
<h1>Traktát o magii Erinorské</h1>
<p>Vím, že toto mé pojednání je velice odvážné a jako takové stojí samo daleko za hranicí zákonů Erinoru. Dovoluji si zde však tvrdit, že magie na Erinoru skutečně existovala, ba co více existuje dodnes. Popírat zašlou moc a slávu magie je přinejmenším hrubě pošetilé, lze bez pochybností tvrdit, že stála u samotného zrodu dnešní vyspělé kultury naší země. Zde si dovolím vzácnému učenému čtenáři vylíčit ve zkratce a srozumitelně historii její moci, vzestupu i pádu.
</p><p>Je téměř s jistotou prokázáno (nejen mými dlouholetými bádáními, mnoho mích kolegů i spisy těch již zesnulých Vám toto potvrdí), že v dávných časech se vyvíjela magie současně s vědou a kulturou, vzájemně propojeně pomáhaly si v cestě k vyššímu vědění, rozvíjely jedna druhou, ruku v ruce téměř sestersky stoupaly k výšinám. V těchto dobách byli čarodějníci a mistři věd magických drženi ve veliké úctě a vážnosti všemi lidmi Erinoru. Jejich umění potřebovali všichni, pomoc si nižádný nedovolil odmítnout, ba žádána byla a hodnocena nejen společensky i ve zlatě ryze královsky. Rodinám bylo ctí mít syna magika, šlechtickým dvorům prestiží a městům nutností. Magie ve své moci dokázala mnohé dnes nemyslitelné, ovlivnit počasí i vyléčit dobytek, vůlí přenášet zprávy i ovládat lidi, krotit vodu i oheň. Dokázala ovládat lidské duše, zemřelého přivézt k životu z cesty, ze níž se nevrací zpět. A bez ustání její síla rostla rozvíjena komunitou magiků všech národů.
</p><p>To však nemohlo mít trvání věčně, jednoho dne magie přestoupila jakýsi vrchol, vymkla se kontrole svých pánů a nezřízeně zaplavila celý svět. Pod jejím vlivem lidé přicházeli o rozum, věci se měnili, zákony Boží i logické platnosti pozbývaly. Čarodějníci všeho světa se spojili ve svorném boji za znovunabytí vlády nad nezkrotným živlem, každý, kdo projevoval známky nadání přiložil ruku (tedy mysl, řečeno přesněji) ke společnému dílu. Toto neštěstí si vyžádalo mnoho obětí na životech ze stran mágů, nejen jich však, postiženi byli všichni myslící tvorové a mnoho obyvatel Erinoru zaplatilo za pošetilost mágů a jejich touhu po nekonečné moci životem.
</p><p>Živel magický se nakonec podařilo přivézt zpět pod kontrolu, však prostí lidé nehodlali magiky mezi sebou dále trpět. Nenávist a bolest ze ztrát vedla ke krvavým čistkám na všech kouzel znalých, vyústila pak roku 627 v Dekret Eirský, jenž oficiálně zakázal provozování jakýchkoli čar pod pohružkou smrti.
</p><p>Magie však tímto nezmizela z povrchu světa. Ustoupila jen kamsi hluboko do pozadí, slaboučká a v utajení téměř zapomenutá všemi. Mezi lidmi se však i nadále čas od času našel někdo, kdo si s ní začal pohrávat či četl zakázané magické spisy. Tito lidé pak za záhadných okolností mizeli, snad spolknuti magií, jak tvrdí nevzdělanci. Nám je však jasné, že za tímto stojí, ač utajen, stát.
</p><p>I dnes se přes všechny snahy o úplné vymícení občas objeví někdo s nadáním a, co hůř, vůlí kouzla studovat. Tito lidé žijí obyčejné občanské životy, utajeně se setkávají a starají se, aby sestra vědy a kultury nebyla nikdy zapomenuta.
</p><p>Netroufám si posuzovat, za to je dobře, či nikoli, děje se to však. Vím, že pokud se toto mé dílo dostane do rukou státní moci, zaplatím za ně nejspíše nejvyšší cenu. I přes to však cítím svou zodpovědnost za informování lidu o historii a stavu údajně neexistující síly zvané magie.
</p>