title = "Stránky LARPu Erinor (pořádané skupinou Pilirion) &ndash; Svět";
keywords = "larp, erinor, fantasy, dřevárny, roleplay, svět";
description = "Stránky LARPu Erinor - sekce svět";

Sem lze napsat libovolný komentář, nebude zobrazen. Zobrazí se pouze text pod čarou.
----------
<h1>Erinor XIII. &ndash;  Kočičí zaklínání</h1>
<h2>Prolog</h2>
<p>Stěny potemnělé místnosti osvětlovalo mihotavé světlo svíčky. S každým silným poryvem větru se však místnost na několik vteřin ponořila do tmy. Na zavřené okenice bubnovaly kapky a žadonily o možnost vejít dál. Záblesk a silný hrom donutil přítomné k výměně ustrašených pohledů. Po chvíli se všichni uklidnili a opět se posadili k malému stolku uprostřed místnosti. 
   </p><p>Skřípavý zvuk doprovázel cestování malé kamenné destičky, která za sebou zanechávala v dubovém masivu vyrytou čáru. Vosk svíce se pomalu roztékal po stole a než dosáhl vyryté drážky, všichni přítomní dali ruce pryč.  Sledovali, jak se černý proužek parafínu rozběhl na cestu po stole. Během mžiku byl celý vyrytý ornament zaplněný. Svíce zhasla a místnost se ponořila do tmy. Všem přítomným probíhal mráz po zádech a nikdo se neodvážil ani hlesnout. Ač vítr kvílel a kapky se dožadovaly pozornosti, stále to nebyly zvuky, na které čekali. Prásk a malými namodralými plamínky začal hořet celý symbol. 
   </p><p>…Strašlivá zima až na kost probíhala celým tělem. Jedinou niť suchou na sobě neměli, ale stále vzdorovali počasí jen, aby se nemuseli vrátit dovnitř. Nikoho nemohli požádat o přístřeší, protože by se příliš vyptával…
   </p><p>…Mladá dívka jemných rysů se procházela po zablácené ulici městečka. Její bílé šaty jakoby zářily. V rukou si nesla bílou chlupatou kočku, která svými pohyby jasně dávala najevo, že s ní nebude zacházeno jako s klubkem. Záblesk. Hrom. Kapky deště, zima a nikde ani noha, natož dívka s chundelatou kočkou. Nic víc…
</p><p>Až časně ráno za šera se odvážili vejít dovnitř. V místnosti nikdo nebyl, vévodil jí pouze pěkný dobový stolek, u něj už pouze tři židle a černá růže.    
</p><p>„Tak a teď už do hajan! Zbytek příběhu zase zítra.“
</p>
<h2>Úvod</h2>
   <p>Od prolomení jižní hranice s elfy uplynulo již deset let. Nakonec jim došel dech a sami začali vyjednávat.
 </p><p>Zeměpisně se přesuneme na sever do Nolgitských plání, kterými se klikatí obří veletok Lithénu, řeka Ogda, a její přítok Skeleftearen. Tato oblast je známá kopcovitým terénem, tisíce jezery a stále kvetoucím vřesem. Před třemi staletími byla oblast plná neprostupných lesů, ale těžba rud to změnila. Přišlo sem obrovské množství lidí najít si svojí stříbrnou horečku. Mnoho jich tady nedokázalo přežít a položilo za svoji touhu život. Ostatní založili města, cechy, hrady a vykořistili z tohoto kousku země, co se dalo.
 </p><p>Nic ale netrvá věčně, a tak i peníze, lidé i úspěch odešli. Brzy už nebylo, co by tato drsná země nabídla, jen nečas a špatnou půdu. Postupně ji tedy lidé začali houfně opouštět. Nezbylo tu skoro nic. Dokonce hrady a tvrze postavené na ochranu bohatství již neměly smysl. Zůstaly s chabou posádkou na okraji zájmu a po vyhlášení federace pozbyly smysl úplně. Pomalu se krajina vzpamatovávala z utrpěných ran, ale i ty nakonec pohřbil čas a příběh o slávě zelených pahorků se stal legendou.   
 </p><p>Oblast tím proslula jako země vysídlenců. Místo odkud většina lidí odešla za lepším již před staletími. Dech a pokrok zbytku federace sem dopadá velmi zvolna, a proto si většina obyvatel ponechává staré zvyky a legendy, které jsou pro tento kraj tak typické. Společně s opuštěnými sídly, hrady starých pánů, rozlehlými bažinami a blízkými horami není divu, že místní lidé věří na strašidla. Jejich pohádky se ve federaci dokonce prodávají v knižní podobě. Místní lidé ale věří a nenechají si nic vymluvit. Jsou tak neoblomní, že postupně vyprchala i síla kněží a poutníků ukázat jim tu správnou cestu. Spokojili se jednoduše s tím, že vyznávají bohy pantheonu a to, že věří ještě na skřítky, šotky a víly, na tom nic nemění. 
 </p><p>Náš díl se odehrává v městečku Lochder. Kdysi to bylo velké město, které bylo jednou z přístavních bran do oblasti. V dnešních dobách tu žije sotva třetina původního počtu lidí. Zbytečné domy a stavby byly postupem času zbořeny a rozebrány jako materiál na nové, a tak už ani není bývalá sláva městečka poznat. V centru městečka je tvrz barona ………. a několik bohatých staveb. 
 </p><p>V poslední době městečkem otřásá neštěstí dvou vedlejších vesnic při březích jezera Loch Nass, kdy po dlouhotrvajících lijácích přišly sesuvy půdy, které přehradily řeku vedoucí z jezera, a jeho hladina se tak rychle zvýšila a vesnice zatopila. 
 </p><p>Co bude dál s obyvateli vedlejších vesnic? Zatím jsou mezi přáteli a čeká se, až započne stavba nového městečka, které by ves nahradilo. Všichni čekají, až se objeví znamení, které by povolilo stavbu na bezpečném místě, aby znovu ke katastrofě nedošlo. Jsou však tací, kteří starým legendám nevěří, a nejraději by se do stavby nového městečka pustili hned. Dokonce prohledávají úpatí hor, kde podle legend nesměli trpaslíci kopat, protože je to území skřítků. Ačkoli nikdo nikdy nepřizná přímo, že skřítka viděl, všichni jsou plní obav. Nikdy se tu podobná katastrofa nestala, tak proč teď. A to jsou tu takové lijáky každých deset let. Dokonce bylo posláno pro známé vyšší alchymisty, aby zjistili co se tu děje. Na jednom se ale shodnou všichni, tam, kde městečko stálo, už nikdy stát nesmí.  
</p>


