title = "Stránky LARPu Erinor (pořádané skupinou Pilirion) &ndash; pořádané: Chrám pokroku";
keywords = "larp, erinor, fantasy, dřevárny, roleplay, svět, pořádané, chrám, pokrok";
description = "Stránky LARPu Erinor, sekce pořádané, Chrám pokroku";

Sem lze napsat libovolný komentář, nebude zobrazen. Zobrazí se pouze text pod čarou.
----------
<h1>Erinor VII. &ndash; Chrám pokroku</h1>
<div class="fotky">
<a href="img/fotky/er7/001.jpg" class="thumb"><img src="img/fotky/thumbs/er7/001.jpg"></a>
<a href="img/fotky/er7/002.jpg" class="thumb"><img src="img/fotky/thumbs/er7/002.jpg"></a>
<a href="img/fotky/er7/003.jpg" class="thumb"><img src="img/fotky/thumbs/er7/003.jpg"></a>
<a href="img/fotky/er7/004.jpg" class="thumb"><img src="img/fotky/thumbs/er7/004.jpg"></a>
<a href="img/fotky/er7/005.jpg" class="thumb"><img src="img/fotky/thumbs/er7/005.jpg"></a>
<a href="img/fotky/er7/006.jpg" class="thumb"><img src="img/fotky/thumbs/er7/006.jpg"></a>
<a href="img/fotky/er7/007.jpg" class="thumb"><img src="img/fotky/thumbs/er7/007.jpg"></a>
<a href="img/fotky/er7/008.jpg" class="thumb"><img src="img/fotky/thumbs/er7/008.jpg"></a>
<a href="img/fotky/er7/009.jpg" class="thumb"><img src="img/fotky/thumbs/er7/009.jpg"></a>
<a href="img/fotky/er7/010.jpg" class="thumb"><img src="img/fotky/thumbs/er7/010.jpg"></a>
<a href="img/fotky/er7/011.jpg" class="thumb"><img src="img/fotky/thumbs/er7/011.jpg"></a>
<a href="img/fotky/er7/012.jpg" class="thumb"><img src="img/fotky/thumbs/er7/012.jpg"></a>
<a href="img/fotky/er7/013.jpg" class="thumb"><img src="img/fotky/thumbs/er7/013.jpg"></a>
<a href="img/fotky/er7/014.jpg" class="thumb"><img src="img/fotky/thumbs/er7/014.jpg"></a>
<a href="img/fotky/er7/015.jpg" class="thumb"><img src="img/fotky/thumbs/er7/015.jpg"></a>
<a href="img/fotky/er7/016.jpg" class="thumb"><img src="img/fotky/thumbs/er7/016.jpg"></a>
<a href="img/fotky/er7/017.jpg" class="thumb"><img src="img/fotky/thumbs/er7/017.jpg"></a>
<a href="img/fotky/er7/018.jpg" class="thumb"><img src="img/fotky/thumbs/er7/018.jpg"></a>
<a href="img/fotky/er7/019.jpg" class="thumb"><img src="img/fotky/thumbs/er7/019.jpg"></a>
<a href="img/fotky/er7/020.jpg" class="thumb"><img src="img/fotky/thumbs/er7/020.jpg"></a>
<a href="img/fotky/er7/021.jpg" class="thumb"><img src="img/fotky/thumbs/er7/021.jpg"></a>
</div>
<p>Další sadu tak 20 fotek najdete na stránkách <a href="http://pilirion.ic.cz">Pilirionu</a><br>Skvěle komentované <a href="http://veskra.rajce.idnes.cz/vyber/">fotky od Veskry</a></p>
<h3>Epilog</h3>
<p>Asi dva týdny po uplynulém dění přiběhl z nížin podivný posel. Ten chlapec nebyl ještě ani zdaleka dospělý a těžko říci, za kým sem vážil sám tak spěšnou a namáhavou cestu z vesnice na úbočí hor. Celý uřícený, zablácený a vyčerpaný se zastavil na návsi, trochu se vydýchal a zavolal: "Lidi poslouchejte mě teď všichni! Poslouchejte!" Pár očí v okolí se k němu zvědavě obrátilo. "Dole pod horama se formuje Soldie. A táhne sem, do Zaluže! V Haszowě nabrali poslední lidi a jdou do hor. Jsou jich tisíce, tolik soldátů najednou jste ještě neviděli!" Pak chlapec zmlkl a rozhlížel se po nastalém tichu na návsi vesnice. Zjevně v davu hledal nějakou známou tvář. Za krátkou chvíli už ho za košili za krkem držel jeden muž z hlídky a třásl s ním: "Je to pravda, co říkáš, chlapče?" "Přesně tak jak jsem to řekl, pane," vyděšeně odpověděl.
</p><p>Brzy město zašumělo neklidem, pak se rozpoutala panika. Kdekdo balil věci a chystal se ke kvapnému odchodu. Soldie, to nejen neznačí nic dobrého. Tahle zpráva naopak přináší velice nepěknou situaci. Soldáti potlačují místní povstání, nepokoje a rozhodují separatistické války. Potlačují protifederativní činnost a ruší velké spolky náboženských heretiků. A co budou asi hledat tady? Klidné bydlení na zimu to jistě nebude. A to přitom místní správa i garda vykazovala v poslední době docela slušné výsledky v přeměně této díry na platnou součást federace i v těžbě zlata na Chrám pokroku.
</p><p>Mnoho lidí se tiše vytratilo. Ostatní pak znepokojeně čekali jak to dopadne. Přespříští den přišli soldáti. Všechno převrátili vzhůru nohama. A když říkám všechno, myslím tím opravdu všechno. Nenechali tu kámen na kameni. Proběhli rozsáhlé šťáry a prohledali i všechny lidi. Mnozí prostě zmizeli. Městečko zůstalo neporušené, ale pyromancerská kohorta si poradila s nově vyrostlými chrámy. Bylo slyšet série mohutných výbuchů po mnoho hodin a dnů. Celá místní inteligence se kamsi vytratila. Kdo neutekl sám, byl převelen, a nebo prostě zabit. Chrámy běžných náboženství najednou zpustly, lidé už nějak přestali prahnout po víře v takovémto čase a taky bez svých náboženských vůdců. Všechno zlato, včetně šperků, které našli u běžných lidí vojáci pobrali a poslali kolonou vozů do Chrámu pokroku. Sebrali hodně peněz, jídla a popravdě, občas se i ženy těžko bránily. A kdo se snad chtěl soldiím vzepřít a bránit se jejich praktikám, byl prostě zabit jako vzor všem ostatním.
</p><p>Domorodce pak vyhnali soldáti výše do hor, sotva stihli pobrat svůj majetek a odehnat alespoň část stáda. Zbytek prostě vojáci zkonfiskovali. A šamanka kamsi v nastalé vřavě zmizela a už ji její kmen také nikdy nespatřil. Domorodci vypráví, že musela před soldáty utéct až na vrchol nejvyšší hory, kde ji přijal pod ochranu sám zlý duch hor.
</p><p>Kapitána hlídky prý soldie ušetřily. Ten nešťastný muž byl konečně povýšen a převelen do jakéhosi bezvýznamného městečka pod horami, kde se stal kapitánem místní gardy. Ve městě, kde se stane jedna vražda za rok a každého zloděje můžete znát jménem. Jeho lidé odešli loajálně s ním.
</p><p>Místní Lithénský úředník a výkupce zlata byl na zimu převelen přímo do chrámu pokroku. Asi ho federace chtěla mít raději pod kontrolou. Přeci jen, pero je silnější meče.
</p><p>Dál se pak vypráví jeden prazvláštní příběh o kohortě, která se celá vypařila. Z ničeho nic, nezbylo po ní víc, než trocha popela a hodně dýmu. Žádné stopy boje, žádná těla ani krev. Asi si je za nepěkné chování k místním obyvatelstvu zavolal k sobě sám Thanatos, aniž by se obtěžoval nechat jejich tělesné schránky umírat. Nebo to možná bylo docela jinak. Po jejich zmizení byl na tom místě viděn jediný malý a velice veselý chlapec. O další kohortě, která byla zrovna nablízku se proslýchá, že byla bohatě odměněna a krátce nato odvelena do jižního pohraničí bojovat do nekonečné marné války s elfími povstalci, odkud se nikdo z vojáků už nevrátil. Ale chlapce už také nikdo nikdy neviděl.
</p><p>Několik týdnů nato soldie zase odtáhly. Na zimu by zde nenašli živobytí, místní tuhý kraj by je prostě po tak dlouhý čas neuživil a v době, kdy jsou průsmyky zaváty sněhem, byli už dávno zpět v srdci federace. Po nich tu zbyla učiněná spoušť. Mnoho lidí ještě před zimou po jejich odchodu následovala vojáky také do nížin. Celkem zde zůstala tak polovina lidí, když přišla do hor zima. Dohlíželo na ně několik soldátů, které zde armáda zanechala místo hlídky. A ano, starostka strávila celou tu dobu svázaná ve sklepě budovy hlídky, protože se stále všemožně snažila soldáty vyhnat a chránit svoje městečko. Rozvázali jí, až když bylo po všem. Nebyla přece nebezpečná a městečko vedla dobře. Vše bylo té zimy ponuré, tiché, nikdo nesnil o ničem jiném, než o míru, klidu a návratu tradičního zalužského nudného pokoje vládnoucího zde po celé uplynulé dva roky.
</p>

<h3>Prolog</h3>
<p>První zima v horách byla velice krutá. Už v prvních týdnech Podzimu se z nebe začala valit mračna sněhu bičující vesnice v prudkých bouřích. Mnoho kolonistů nepřipravených na zimu se potýkalo s vážnými potížemi, jejich domy nebyly stavěné na tyto extrémní podmínky, sami neměli dostatek teplého oblečení ani připravené palivo. Když pak okolo počátku Zimy přišla tradiční asi týdenní obleva a průsmyky se staly průchozí alespoň pro pěší, mnoho lidí se rozhodlo vrátit do svého bídného, ale bezpečného života v centru Lithénu.
</p><p>Ti, kteří přečkali až do jara, však už neodešli. Naopak se začala civilizovaná populace Zaľuže rozrůstat. Důvod se objevil už na podzim - ZLATO. Do hor se za vidinou zisku hrnuly tisíce lidí, ale federace zareagovala nepředvídatelně hbitě novým výnosem, který ukládal na dolování zlata vysokou daň. Abych lehce shrnula dění ve federaci, sílící moc Sněmu a utěšená ekonomická situace dovolila zahájit monumentální projekt, stavbu nového sídla Sněmu, Chrámu pokroku, nového města na zeleném drnu, centra politické síly i kultury federace, města z kamene a hlavně ze zaľužského zlata (nebo spíše za zaľužské zlato). Každý zlatokop či obchodník se zlatem podle výnosu získává tu ohromnou čest stát se stavitelem Chrámu pokroku a přispět tak svým dílem. V praxi to znamenalo asi devadesáti procentní daň a povinné těžební kvóty. I přes to se ale dalo v Zaľuži při troše štěstí neuvěřitelně zbohatnout. A kde je zlato a vysoké daně, tam bují zločin - banditizmus, pašeráctví, krácení daně. A také garda, milice, inkvizice a popravy bez justice.
</p><p>V jiných kruzích se ale mluví o odlišném Chrámu pokroku. Ne gigantické stavbě v srdci říše. Docela jiném chrámu - lidské duši do které má nová doba přinést veliký pokrok. Tuhle vizi mezi sebou tiše šíří kněží povolených i zakázaných náboženství a ti kdo se za ně vydávají. Chrám pokroku má být příchod nové filozofie vedoucí k velkému vzestupu člověka, nového, lepšího. A čelní myšlenka je obnovení náboženské tolerance, téma o kterém se často hovoří v tajných kruzích jako o velikém snu, prostředku i cíli . Zatím nesplnitelném, ale žádná stavba (tedy skoro žádná) nevyroste přes noc. Dalším pokrokem je bádání v naukách ještě tajemnějších než jsou ty církevní… A tyto "kruhy" láká do Zaľuže tajemství okolo podivných chrámů v horách z nichž jedem právě přes noc vyrostl…
</p>
<h3>Výnos federace Lithénu ze 2. dne 4. týdne Jara 1432 o dani z těžby zlata a zákon proti znehodnocování ceny zlata</h3>
<p>Vzhledem k zahájení stavby nového centra říše, Chrámu pokroku, zasedacího sídla Sněmu a zástupců všech států Lithénu, dále pak univerzitního a chrámového města v bezprostředním okolí Chrámu, zavádí federace novou mimořádnou daň z těžby zlata po dobu následujících čtrnácti let. Tato daň bude použita na stavbu Chrámu pokroku a všichni plátci se takto zaslouží o jeho stavbu a posílení moci federace. Který občan federace bude po dobu 7 let poctivě daň odváděti, dostane se mu té cit státi se majitelem pozemku pro stavbu domu a řemeslné dílny v bezprostřední blízkosti Chrámu pokroku a povolení zde bydlet a podnikat.
</p><p>Placení daně bude toto: vždy dvakrát denně, hodinu po poledni a hodinu pře soumrakem bude každý, kdo těží zlato povinen odevzdat ho výkupci. Zaplaceno dostane maximálně za dvě jednotky a to podle současného kurzu ceny zlata ve federaci. Kdo bude přistižen při tom, že těží zlato a neodvádí jej nebo si jeho část nelegálně ponechává, bude souzen a potrestán podle zákonů federace pro krácení daně. Se zlatem smí nadále obchodovat pouze osoby k tomu pověřené federací a i ty smí prodávat třetí straně pouze obvyklé množství zlata, každý kupec do deseti jednotek denně. V této sumě je už zahrnuta i cena nákupní. Ostatní zlato je povinen bez poplatku odvést státu.
</p><p>Kdo se bude vyhýbati placení těchto daní bude souzen podle zákonů federace, za lehký přečin bude mu uložena pokuta, za těžší vězení. Za zvláště nebezpečné přečiny může být uložen i vyšší trest např. useknutí ruky.
</p><p>Pro ostatní občany federace dále přichází od téhož termínu do platnosti zákon proti devalvaci ceny zlata, podle kterého nesmí žádný občan federace, který není výkupce zlata vlastnit více jak 5 jednotek zlata najednou. Kdo poruší toto, bude souzen jako pašerák a může být i popraven. Zákon se nevztahuje na horníky pokud zlato odevzdají ve stanoveném termínu výkupci. </p>