title = "Stránky LARPu Erinor (pořádané skupinou Pilirion) &ndash; knihovna: Měsíční kopec";
keywords = "larp, erinor, fantasy, dřevárny, roleplay, povídka, knihovna, měsíční, kopec";
description = "Stránky LARPu Erinor, sekce knihovna, povídka Měsíční kopec";

Sem lze napsat libovolný komentář, nebude zobrazen. Zobrazí se pouze text pod čarou.
----------
<h1>Měsíční kopec</h1>

<p>Na indigovém bezoblačném nebi zářil měsíc. Kulatý jako kolo od vozu a bledý tak, jak může být jen měsíční svit. Byla pravá půlnoc nejdelší noci roku. Lidé podvědomě zavírali okenice a dveře na petlice a k posteli si před spaním brali ostrý dřevěný kůl pod polštář. Všichni šli brzy spát, protože věděli, co se v tuhle dobu bude dít.
</p><p>Na Měsíčním kopci tak jako vždy o úplňku tančily víly. Říkalo se o nich, že jsou tak lehoučké, že nenechávají v lístcích a trávě ani stopu a že když tančí, mají nad hlavami svatozář. Jejich krutý zvonivý smích byl prý slyšet po větru. Víly začínaly tančit, ale ještě předtím se podívaly nahoru na kopec. Před hustým, tmavým lesem stály dva osamocené, vysoké smrky, které odolávaly zoubkům času již přes dvě stovky let. Podle lidí ze Smutné za to mohla kouzla a magie starých časů.
</p><p>Popravdě řečeno, ve Smutné už nebylo tolik skutečné magie jako kdysi. Lidé měli mnohem raději kouzelníky z měst, kteří sem jezdili vždycky na jaře a předváděli triky s kartami a jednoduché legrácky s kloboukem a holubem. Byly to obyčejné hlouposti, kterým by po chvíli usilovného uvažování přišlo na kloub i malé děcko, ale lidé je měli rádi. Čarodějky, které zbývaly, se s postupem let staly vlastně jen obyčejnými kořenářkami, žádní čarodějové a opravdoví mágové už nezbyli. Kromě Ní. Ona byla poslední mocnou čarodějkou, poslední, která si uchovala moc starých časů. Pobaveně se zasmála. Dnes bude dlouhá noc a ještě delší den!
</p><br>
<p>Na dlážděném mostu, který vedl od věků přes řeku Stinnou, zarachotila kola vozu. Do Smutné jen málokdy přijížděli cizinci, zvláště v téhle sychravé době. Stromy se halily do své typické podzimní melancholie a celý kraj vypadal nešťastně, zkroucené hnědavé listí se válelo v blátivých kalužích při cestě. Vůz zastavil nedaleko místního hostince, jediného. "Bude to šest a půl šilinku," zasyčel starý vozka. Z vozu vystoupil mladý muž s děravou brašnou a vylovil několik mincí z kapsy kabátu. Měl špičatou bradu, nezdravě bílý obličej, temné oči, pod nimiž se rýsovaly tmavé kruhy únavy, a neuvěřitelné charisma. Ale když se na něj člověk podíval blíže, zjistil, že oheň těch očí dávno vyhasl. Byly to oči člověka, který už viděl věci, jež se vymykají všem řádům a pravidlům, veškeré logice i hranicím lidskosti. Oči člověka, který touží jen po klidu a zapomnění.
</p><p>Prošel kolem domu, patřícího místnímu starostovi. Všichni měli zavřené okenice, aby lezavý vítr nezhasínal oheň v krbech. Zaklepal na dveře hostince a přitáhl si kabát blíže k tělu; loupající se vývěsní tabule se výhrůžně zahoupala na zrezlém řetězu. Vítr se protáhl ulicemi a se svou rmutnou hvízdavou baladou narážel do zdí domů. Cizinec otevřel dveře a prošel kolem hloučku usmívajících se mužů, kteří čekali na další rundu piva. Sporé světlo petrolejky zavěšené pod stropem si pohrávalo se stíny v koutech. Opatrně se prosmekl mezi plně obsazenými stolky, až se dostal k jednomu prázdnému. Sedl si a odhrnul si z očí tmavé vlasy. Netrvalo dlouho a přiběhl k němu menší obtloustlý muž s korbelem v ruce. "Přání?" zeptal se nevrle. Cizinec k němu unaveně zvedl oči. "Režnou," odpověděl. Vytáhl z kapsy několik mincí a přepočítal je.Šest. Snad to bude stačit. Hostinský na sebe dal dlouho čekat, ale nakonec požadovaný nápoj donesl. "Co jsem dlužný?" zeptal se cizinec. "Čtyři traéky, jestli to nebude nic jiného," odsekl podrážděně hospodský. "Jistě," odpověděl cizinec, odpočítal potřebnou sumu a přisunul ji k obtloustlému hostinskému. Ten se odpotácel kulhavým krokem pryč. Cizinec se za ním lehce pootočil. Pak se obrátil zpět ke své sklenici. Zatraceně drahá, ale zatraceně účinná. Alespoň v to doufal. Zavřel oči a obrátil ji do sebe dnem vzhůru. Do očí mu vhrkly slzy a pocítil chuť nalít do sebe ještě vědro vody. Nakonec ze sebe setřásl pocit pálení a kuckání. Zaslechl za sebou výbuch smíchu a hnusný dávivý zvuk. Najednou mu někdo poklepal na rameno. Otočil se. "Dobrý večer, mladíku. Jestli dobře vidím, tak jste cizinec. Jak se jmenujete?" zeptal se ho postarší muž. Vypadal přívětivě a i přes napudrovanou bílou paruku a upravený oděv, který dával najevo vysoké postavení, se usmíval. Cizinec se lehce pousmál, ale v té grimase nebylo nic veselého. "Jsem Rovert Drinesey, hledám tady místo, kde bych se mohl ubytovat," odpověděl. Muž se pousmál. "Mé jméno je Aldert d'Corde, jsem zde starostou. Zajisté tu nějaké místo najdete. Zkuste se poptat u vdovy Bulgesové, možná by u ní byla i nějaká práce," řekl mile starosta. Pak jeho pohled sklouzl k prázdné sklenici na stole. "Příteli, snad nepijete tu břečku, co hostinský považuje za drenovicu?" zeptal se káravě. Rovert pokýval hlavou. "Lepší to než nic," odpověděl. Starosta pokrčil rameny a pak se ohlédl. "No, kdybyste potřeboval s něčím poradit, můj dům a zajisté i dveře těch ostatních, vám budou otevřeny," zvedl se a odešel. Robert chvíli seděl a díval se na dno sklenice. Ještě před měsícem by se režné ani nedotkl. Zvedl se a vykročil ke dveřím. Jenže před měsícem se stalo tolik věcí, které se stát neměly, že nějaká režná drenovica už ho nemůže rozházet. Tak především před měsícem si měl prohlížet rakev zevnitř, což teď také nedělá.
</p><p>Zastavil se, jako by nad něčím přemýšlel. Otočil se nejistě k hloučku napůl opilých mužů. "Promiňte, ale nevíte, kde bych nalezl madame Bulgesovou?" zeptal se nejistě. Jejich smích utichl jako by ho uťal, byl slyšet jen tichý praskot ohně a skřípění hadru, jímž hostinský leštil zasychající sklenice. "U hřbitova, vedle márnice," řekl jeden z nich po chvíli. Druhý se zakuckal, až vyprskl pivo na protější stůl. "Čarodějky," odplivl si. Rovert nadzvedl obočí, neslyšně si povzdychl a pro jistotu se vzdálil.
</p><br>
<p>Zešeřelá krajina vypadala hrozivě a nenávistně. Světlo, jež procházelo prořídlými korunami stromů, vrhalo na zem bizarní tvary. Nikdo se neodvažoval nahoru k lesům na Měsíčním kopci. Zvláště ne teď, když tam měly tančit víly. Povídalo se totiž, že ten, kdo viděl víly při jejich tanci, se již nikdy nedožil rána a zmizel za podivných okolností. Ale od lesa se blížilo blikotající světlo. Jakási vysoká postava bojovala se skučícím větrem a drala se k palouku. Za chvíli došla až k houštinám; posadila se na zem, sfoukla takřka vyhořelou svíci v popraskané lampě a dýchla si na promrzlé prsty. Každou chvíli, už každou chvíli začnou tančit. A on bude první, kdo je kdy vid... ozval se strašlivý výkřik vynucený bolestnou agonií utnutý v půli.
</p><p>Do rozbředlé hlíny se zabořila rozbitá svítilna, z níž se kouřilo. A vítr ji za chvilku přikryl dalšími mokrými listy.
</p><br>
<p>Na dveře se ozvalo nenápadné zaklepání. Rovert čekal, až se otevřou. Výhrůžně zaskřípaly a na prahu se objevila tmavá silueta kostnaté hubené ženy. "Co mi chcete?" zeptala se stará žena s vějířem vrásek ve tváři. V jedné ruce držela svícen, ve druhé sekáček na maso. Rovert sklouzl pohledem z její tváře na ruce a poněkud ustoupil. "Ále, to nic," uklidňovala ho nepříjemně a schovala ruku se sekáčkem za záda. "Co jste zač?" vyzvídala a posvítila mu do tváře. "Jsem tu cizí a hledám ubytování," vyhrkl dříve, než stačila zavřít dveře. "Tak jdi hledat jinde," odsekla a zabouchla. Trpělivě znovu zaklepal. Dveře se rozlétly a žena za nimi držela sekáček nepřiměřeně vysoko. "Co mi chcete? Odejděte odsud!" zavrčela krákavě a ohnala se po něm. "Sháním ubytování, řekli mi, že se mám zeptat vás," pokusil se. "A jméno?" pokračovala jako u křížového výslechu. "Jmenuji se Rovert Drinesey, nezdržím se dlouho," odpověděl. "Hm," přeměřila si ho od hlavy k patě. "Pokud máš žaludek na to, bydlet vedle márnice, tak prosím," odsekla a pustila ho dovnitř. Rovertův pohled říkal, že jeho žaludek už vydrží všechno. Vylezla do patra po schodech, které vypadaly značně staře, a otevřela dveře do pokoje pro hosty. "Prosím," řekla a podala mu svícen. "Jestli se vám nelíbí, můžete jít jinam," dodala výhrůžně. Prošel do pokoje a počkal, až za ním zavře s prásknutím dveře. Místnost byla poměrně malá a podle zatuchlého pachu, který se vznášel kolem jako nepříjemná mlha, ani příliš používaná. V rohu vedle okna stála obyčejná postel s rozvrzanou pelestí, na druhé straně naproti dveřím laciný stůl se třemi zásuvkami a židle. A nakonec v rohu nalevo ode dveří byla skříň.
<p>Rovert přešel ke stolku a položil na něj tašku. Pak přešel k oknu a rozevřel ho dokořán. Byla chladná jiskrná noc. Nebe bylo poseto tisícem hvězd a velký koláčovitý měsíc osvětloval vesnici.
</p><br>
<p>
Najednou zaslechl vyděšený šepot zespodu. Nevydržel a nepatrně otevřel dveře, aby zaslechl útržky hovoru. "Zmizte, víte, že sem nesmíte."<br>
"Vím, ale d'Corde potřebuje Vaši pomoc."<br>
"A proč?"<br>
"Shiver."<br>
"Co s ním?" Nově příchozí zašeptal něco tak tiše, že to nahoru nezaznělo.<br>
"Ne!"<br>
"Ale ano."<br>
"Jdeme."<br>
"Slyšel jsem, že tu máte nějakého cizince?"<br>
</p>
<p>"Trouba. Za týden práskne do bot." K Rovertovi dolehl klapot bot a zavírání dveří. A pak už jen ticho. Sešel opatrně dolů a podíval se z okna. Vdova Bulgesová a neznámý muž mířili dozadu, k lesu. Nenesli s sebou nic, ani světlo. Rovert se podíval na stůl před krbem. Na papírech, poházených v nesouvislých řadách, byly krví napsány staré runové znaky. Naklonil se k nim, aby si je přečetl. Do místnosti vtrhl ostrý chlad, zažloutlou záclonou v okně zacloumal vítr. Venku se zablesklo, i když na obloze nebyly žádné mraky a začalo pršet. Tohle byly runy, které patřily minulosti, starým časům. Runy, které v sobě skrývaly nedozírnou moc. Rovert je dočetl a zavrtěl hlavou. "To ne," vydechl, spíše pro sebe než komukoliv jinému. Sebral štos papírů ze stolu a podíval se do zapáleného krbu. Slova na papíře šeptala, prosila, vábila...
</p><p>Zvenku k němu dolehl podivný zvonivý smích a skučení větru. Vzpomínky ho pálily a svíraly.
</p><p>"Neboj se, zítra zase přijdu," řekl krásný hlas. Hebký a sladký ale chladně odtažitý. Hřál a zároveň chladil, konejšil a přitom zraňoval. Byl to hlas, kterým by vládl hřích, kdyby uměl mluvit. A patřil té nejnádhernější ženě, kterou kdy viděl. V matném světle hořících svící se zdála jako třepotavý sen, jen slabá vůně, mu říkala, že se mu nezdá. Byla jeho andělem, andělem v krvavě rudých šatech. Rovert se na ni usmál. "Budu doufat," protáhl líně. Zvedla se. Pocítil strašlivé nutkání ji zastavit, něco mu našeptávalo, aby ji neopouštěl. "Imerien, neodcházej ještě," poprosil, i když věděl, že je to zbytečné. Krásná dívka se na něj usmála; ale její tvář zrazovala. Nevěděl proč, ale když udělala krok ke dveřím, měl pocit, že ji ztrácí. "Prosím," zašeptal. Znovu se na něj usmála. "Pořád jsem tady," naklonila hlavu ke straně. Její hlas se táhl jako hustý med. Po svíčce skanula kapička horkého vosku a skápla Rovertovi na ruku. Sykl bolestí. Nechápal význam jejích slov. Jen naslouchal jejímu hlasu. Uklidňoval ho, tak jako vždycky, ale teď ho z nějakého důvodu děsil. Natáhla se a zvedla ze stolu pohár. Pomalu nalila víno z demižonu. "Napij se," řekla podbízivě a podala mu čísi. Něco se v něm vzpíralo, ale jejímu hlasu se nedalo odporovat ... Číše vypadala z ochablých prstů. Sebrala ji a pohladila ho po tváři. "Nemohla jsem jinak. Až se probudíš, nevzpomeneš si na dnešní noc," zašeptala. Pak se zvedla a uhasila svíčku. Vykradla se z pokoje a když si byla jistá, že ji nikdo nevidí, odešla do bezoblačné noci.
</p><br>
<p>Bylo krátce po jedné hodině ráno, když se vdova Bulgesová tiše vrátila zpět. Ráno bylo lezavé a ponuré. Neprůhledná mlha se převalovala mezi domy tak nízko, že nebylo pomalu vidět na krok, slunce ještě nevyšlo. Rovert seděl u stolu. Na rukávu bílé košile měl skvrnu od inkoustu, vedle něj ležel papír s úhledně napsaným vzkazem. Vzpomínky se mu vracely ostřejší než kdy předtím.
</p><p>"Kde je, Calemare?" z jeho hlasu čišely jako severák vtek a strach. Muž u brány si přitáhl kapuci do tváře a mírně se poklonil, když kolem prošel mnich v šedavé kutně. "Odešla." Rovert si prohrábl vlasy. "A víš kam?" Calemar pokrčil rameny a přitáhl koni uzdu. "Možná, ale jak víš, musím zmizet co nejrychleji a moje informace jsou peníze," odpověděl. Rovert prohrábl kapsy a hodil mu pohublý váček mincí. "Potřebuji to vědět," řekl chvatně. Calemar vysypal pár mincí do dlaně a prohlédl si je. Pak přikývl a ukázal směrem k horám. Jejich klenuté štíty sahaly až do mraků a čněly hrozivě jako stíny obrů. "Tři dny cesty na východ najdeš vesnici. Říkala, že odjede tam. Ale Roverte," mluvčí mu opatrně poklepal na rameno, "ona odjela, protože tě chtěla ochránit." Rovert svraštil obočí. "Před čím proboha?" "Před sebou. Odjela, protože ji volá. Ona ji volá, poslední ze Čtyř. Na tu nestačí ani tvé schopnosti." Rovert se podíval k horám a zastínil si oči. "Vím," přikývl krátce. Muž se vyhoupl do sedla a otřásl se, jako by viděl smrt. "Měl bys také vypadnout co nejdřív, viděls, co se stalo Oderovi. A to lidem pomáhal. Nechci tu čekat, až mě pověsí někam na větev, už takhle je to dost zlé," popohnal koně. "Zapomeň na Imerien, Roberte, víš co říká věštba. Víš to myslím si více než dobře." S tím odjel, jen obláčky prachu připomínaly, že tu před chvíli stál kůň. Věštba o Čtyřech velkých, o posledních čarodějích a čarodějnici, kteří slouží zlu. Znalo ji jen pár vyvolených, jen ti, kteří byli u bitvy, kde bylo zlo poraženo. Tři z nich padli; byli příliš hrdí na to, aby se vzdali. Poslední, čarodějnice, se vzdala. Podrobila se, protože věděla, že by ji čekala smrt. Odešla do hor, ale podle věštby, která byla vyslovena, zlo znovu získá vládu nad světem a před tím bude prolita čistá krev, pokud Ji neporazí někdo...
</p><p>Ve tváři měl vidět pochyby. Za týden ho našli mrtvého, lidé ho ubili k smrti. A jeho oči se upíraly k lesu. Ve vzduchu se stále vznášel ten třepotavý smích, ale teď v něm bylo i něco jiného. Smrt. Jen málokdo to mohl cítit a jen málokdo to dokázal poznat. Rovert to věděl. Cítil to. Cítil tepající krev a bolest. A cítil, že je jí, Imerien, souzeno zemřít.
</p><p>&hellip;bude prolita čistá krev, oběť nevinnosti, jež sama s vědomím smrti vstoupí na oltář, a Ona se vrátí a spolu s ní i temná magie, jež pohltí celý svět a zničí vše dobré. Války se potáhnou dlouhé věky a nikdo Ji už nedokáže porazit...
</p><p>Zvedl se a oblékl si kabát. Velice pečlivě zalepil obálku a položil ji na prázdný stůl. Seřízl brk, namočil ho do inkoustu a připsal na útržek papírů krátkou prosbu. Nakonec vysypal na křivou plochu stolu posledních několik mincí. Tušil, že by to mohl změnit, ale nebyl si jistý. Znovu se nadechl. Ten pach smrti byl teď silnější a ostřejší.
</p><p>Od lesa se vzneslo hejno vran.
</p><br>
<p>Rovert prošel ven a zamířil k márnici. Vdova Bulgesová stála na zápraží a věšela nad dveře starou rezavou podkovu. Když ho zahlédla, nerudně se k němu otočila. "Chodíte potichu jako přízrak," zabručela. Rovert neodpověděl. "Co se v noci stalo?" zeptal se. Vdova Bulgesová se na něj ostře podívala. Jeho oči jí říkaly, že to ví, jen se chce ujistit. Začala mít pocit, že ví něco více než ona. Že je mnohem silnější, než se zdá. Slabě přikývla. "Máš doufám silný žaludek," řekla. Pak vešla dovnitř. Na zemi ležela jediná rakev a na u ní pár krvavých stop, které se někdo pokusil setřít hadrem. Odsunula její víko. Místnost naplnil ostrý zápach. Rovert si přidřepl a podíval dovnitř. Člověk nebo to, co kdysi člověkem bývalo, mělo šedozelenou barvu. Celé tělo a hlavně tvář byly pokryty zaschlou krví a na krku měla postava kousance a drápance potažené blankytně modrými stroupky. Vypadalo to, jako by ho napadlo něco skutečně velkého a vydrápalo mu oči. "Byl to soudce Shiver, byl se v noci podívat na kopec," vdova se na Roverta podívala s jistým odhodláním. Tvářil se ustaraně. "Víly?" zeptal se. Přikývla. Povzdechl si. "Musím jít," řekl a zvedl se.
</p><p>Čarodějnice se probrala. Ucítila prudký náraz magie, velkou sílu, která proudila vzduchem. Zvedla se a napřáhla ruku. Do okna vlétla černá vrána a usadila se jí na zápěstí. Chvíli mávala křídly, pak vylétla zase ven. K zemi se sneslo černé pírko. Sebrala ho a křivě se usmála.
</p><p>Rovert prošel tichými ulicemi, dokonce ani vítr se neodvažoval za hranici vesnice. Listí bylo naváté až ke kamenné bráně. Ta možná kdysi, ve starých dobách, sloužila k obraně před žoldáky, kteří často drancovali a plenili menší města a snadno dobytné vesnice za krvavé války. Víno teklo proudem, markytánky na klíně vojáků se smály, opilí muži bez kázně často zabíjeli bezbranné, prostě jen pro tu zábavu z bezmoci své oběti. A mocní, ti kteří válku vyvolali, byli pronásledováni; často byly u cest vidět čarodějnice, které lidé pověsili na větvích suchých stromů nebo upálili. Čarodějové a mágové byli lynčováni, lid si žádal oběti za své utrpení, lid lačnil po krvi. Smrti se téměř nikdo z těch, kdo znali tajemné umění magie, ať už dobré nebo zlé, nevyhnul. Kromě několika šťastlivců. Robert kopl do kamene, který se mu připletl do cesty. Býval by raději, kdyby skončil na šibenici jako jeden z ostatních.
</p><p>Nezastavil před hranicí varovně šustícího lesa, šel dál, až ke starému popraskanému dubu. Možná to byla magie a kouzla, která z celého lesa vysála život. Možná jen strach, kdo ví. Robert byl unavený tak jako nikdy. Zaslechl kroky.
</p><p>"Vždycky jsem věděla, že jsi pošetilý," ozval se hlas, falešný a jedovatý jako hadí jazyk. "Ale když jsem tě viděla přicházet, myslela jsem si, že se mýlím." Otočil se. Stála před ním Ona, čarodějnice vládnoucí černou magií.
</p><p>"Dnes to skončí," řekl pevně.
</p><p>"To ano," připustila. "Ale bude to tvůj konec. Stále jsi ještě tak odhodlaný ji zachránit?" zeptala se. Rovert se nadechl. Pomalu, jako by si užíval ten pocit, kdy může dýchat.
</p><p>"Propusť ji," řekl. Čarodějnice se zasmála a znělo to jako chřestění okovů.
</p><p>"Copak to nevidíš? To ona sama ke mě přišla, ona sama se ze své vůle stala vílou a já ji naučím všem tajům, té opojné sladké chuti zla," řekla. A nakonec, až ji nebudeš potřebovat, ji zabiješ, pomyslel si.
</p><p>"Ne," odpověděl prostě. Čarodějnice se na něj znovu usmála.
</p><p>"Ale když ji propustím a i když mne porazíš a zničíš všechno vědění zla, které střežím jako poslední zbývající, pak stejně nevyhraješ. Protože jí je souzeno zemřít. Tak to říká proroctví, vzpomínáš?" zeptala se. Rovert mlčel. Samozřejmě, že si vzpomínal. A bál se toho. Čarodějnice se najednou změnila. Zvětšila se a její šedé vlasy zmizely. Místo nich ve větru povlávalo hejno vran.
</p><p>"Jsi bláhový, když si myslíš, že mne porazíš!" vykřikla. V ruce se jí objevilo černé světlo a vyšlehlo po něm jako blesk. Stačil uhnout stranou.
</p><p>Na Měsíčním kopci dotančily víly. Naposledy se zatočily vzduchem a chystaly se odejít. Jedna z nic se náhle zarazila. Ostatní se na ni podívaly. "Co se děje?" zeptaly se, jejich hlasy byly tak krásné. Imerien se nadechla se, ale neodpověděla. "Nevím," řekla. Hrdlo se jí sevřelo. Proč lže? Proč to řekla? A najednou pochopila. Snad by nebyl tak pošetilý... Udělala pár kroků až se rozběhla k lesu.
</p><p>Vzduch byl přesycen temnou silou, přeskakovaly v něm barvy magie. Rovert ucítil, jak ho strašlivá síla srazila k zemi. Ze rtu mu tekl pramínek krve. Calemar měl pravdu, jeho schopnosti na Ni nestačí. Zvedl hlavu. Čarodějnice se napnula. "Nemusíš se bát. Ona zemře hned po tobě," a vyslala proti němu další ránu. Ucítil strašlivou, ale přeci jen uspokojivou bolest na prsou. Usmál se. Čarodějnice se chystala k poslednímu úderu. Když si všimla jeho výrazu, zarazila se. "Proč?" zeptala se krátce. Zavřel oči. Zašeptal slova, která nepatřila tomuto času. Zašeptal slova, která byla napsána starými runami a která oplývala nedozírnou silou. Čarodějnice vykřikla, ale pozdě. Uviděl už jen záblesk kouzla, které proti němu vyslala, než zmizela. Její tělo se změnilo v tmavý stín, k zemi se s třepotáním snesl její plášť a změnil se v hejno vran. Věděl, že je konec. Konec bitvy, konec magie světa té dobré i té zlé, konec jeho cesty. Uviděl, jak k němu přibíhá postava, ale nedokázal si vybavit její tvář. "Roverte," ozval se hlas, byl tak hebký, tak uklidňující. Dokázal to. Dokázal změnit její osud. Je volná. Teď už věděl, čí smrt to viděl a s trpkým uspokojením si uvědomoval, že se nemýlil. Sklopil pohled na svou hruď a pak pomalu klesl na zem.
</p>
<br>
<p>Vím, že toto mé pojednání je velice odvážné a jako takové stojí samo daleko za hranicí zákonů Erinoru. Dovoluji si zde však tvrdit, že magie na Erinoru skutečně existovala, ba co více existuje dodnes. Popírat zašlou moc a slávu magie je přinejmenším hrubě pošetilé, lze bez pochybností tvrdit, že stála u samotného zrodu dnešní vyspělé kultury naší země. Zde si dovolím vzácnému učenému čtenáři vylíčit ve zkratce a srozumitelně historii její moci, vzestupu i pádu.
</p><p>Je téměř s jistotou prokázáno (nejen mými dlouholetými bádáními, mnoho mích kolegů i spisy těch již zesnulých Vám toto potvrdí), že v dávných časech se vyvíjela magie současně s vědou a kulturou, vzájemně propojeně pomáhaly si v cestě k vyššímu vědění, rozvíjely jedna druhou, ruku v ruce téměř sestersky stoupaly k výšinám. V těchto dobách byli čarodějníci a mistři věd magických drženi ve veliké úctě a vážnosti všemi lidmi Erinoru. Jejich umění potřebovali všichni, pomoc si nižádný nedovolil odmítnout, ba žádána byla a hodnocena nejen společensky i ve zlatě ryze královsky. Rodinám bylo ctí mít syna magika, šlechtickým dvorům prestiží a městům nutností. Magie ve své moci dokázala mnohé dnes nemyslitelné, ovlivnit počasí i vyléčit dobytek, vůlí přenášet zprávy i ovládat lidi, krotit vodu i oheň. Dokázala ovládat lidské duše, zemřelého přivézt k životu z cesty, ze níž se nevrací zpět. A bez ustání její síla rostla rozvíjena komunitou magiků všech národů.
</p><p>To však nemohlo mít trvání věčně, jednoho dne magie přestoupila jakýsi vrchol, vymkla se kontrole svých pánů a nezřízeně zaplavila celý svět. Pod jejím vlivem lidé přicházeli o rozum, věci se měnili, zákony Boží i logické platnosti pozbývaly. Čarodějníci všeho světa se spojili ve svorném boji za znovunabytí vlády nad nezkrotným živlem, každý, kdo projevoval známky nadání přiložil ruku (tedy mysl, řečeno přesněji) ke společnému dílu. Toto neštěstí si vyžádalo mnoho obětí na životech ze stran mágů, nejen jich však, postiženi byli všichni myslící tvorové a mnoho obyvatel Erinoru zaplatilo za pošetilost mágů a jejich touhu po nekonečné moci životem.
</p><p>Živel magický se nakonec podařilo přivézt zpět pod kontrolu, však prostí lidé nehodlali magiky mezi sebou dále trpět. Nenávist a bolest ze ztrát vedla ke krvavým čistkám na všech kouzel znalých, vyústila pak roku 627 v Dekret Eirský, jenž oficiálně zakázal provozování jakýchkoli čar pod pohružkou smrti.
</p><p>Magie však tímto nezmizela z povrchu světa. Ustoupila jen kamsi hluboko do pozadí, slaboučká a v utajení téměř zapomenutá všemi. Mezi lidmi se však i nadále čas od času našel někdo, kdo si s ní začal pohrávat či četl zakázané magické spisy. Tito lidé pak za záhadných okolností mizeli, snad spolknuti magií, jak tvrdí nevzdělanci. Nám je však jasné, že za tímto stojí, ač utajen, stát.
</p><p>I dnes se přes všechny snahy o úplné vymícení občas objeví někdo s nadáním a, co hůř, vůlí kouzla studovat. Tito lidé žijí obyčejné občanské životy, utajeně se setkávají a starají se, aby sestra vědy a kultury nebyla nikdy zapomenuta.
</p><p>Netroufám si posuzovat, za to je dobře, či nikoli, děje se to však. Vím, že pokud se toto mé dílo dostane do rukou státní moci, zaplatím za ně nejspíše nejvyšší cenu. I přes to však cítím svou zodpovědnost za informování lidu o historii a stavu údajně neexistující síly zvané magie.
</p>