title = "Stránky LARPu Erinor (pořádané skupinou Pilirion) &ndash; svět: náboženské podrobnosti";
keywords = "larp, erinor, fantasy, dřevárny, roleplay, svět, náboženství, podrobnosti";
description = "Stránky LARPu Erinor, sekce svět, náboženské podrobnosti";

Sem lze napsat libovolný komentář, nebude zobrazen. Zobrazí se pouze text pod čarou.
----------
<h1>Náboženství &ndash; bohové</h1>
<p>
Většina obyvatel Lithénu jsou věřící, na ateisty připadá jen malý díl učenců, umělců a vyvrženců. Lithénští věřící uznávají existenci všech sedmi bohů, svoje motlitby však směřují většinou jen k jednomu z nich. Náboženství zde více méně zastupují filozofické směry, ke každému vyznání se pojí určitý způsob života (samozřejmě ne pro všechny vyznavače zcela shodný a přímo dodržovaný). Některá náboženství požadují po svých uctívačích časté motlitby a meditace, z jiných zas zasahuje do života jen filozofie a zásady. Na většině univerzit probíhají neustálé filozoficko - teologické pře a disputace. Vyznavači různých bohů i jednotlivých sekcí a směrů mezi sebou občas vedou boje.
</p><p>
Teď k vlastním kultům a církvím, jejich charakteristice a filozofii:
</p>
<h3>Vyznavači přírody bohyně Natürwanny (též Natirvany)</h3>
<p>Dělí se do tří větví, z nichž každá žije vlastní a zcela svéráznou životní filozofií. Od nejkontroverznější a nejortodoxnější větve to jsou:
</p><p>
<strong>Druidi lesů</strong>: Mezi tyto dá se říci fanatické vyznavače přírody a jejích principů patří asi kolem 3% obyvatel Lithénu, výhradně elfové a lidé. Žijí velice uzavřeně a straní se jakékoli společnosti. Vyznavači se slučují ve společenství v osamělých osadách v lesích a živí se převážně tím, co jim příroda nabídne. Do měst se téměř nevypravují, nemají to ani zapotřebí. Život rostlin a zvířat jim je často milejší, než život lidský, neloví mladé a zdravé kusy i jinak šetří co nejvíce své okolí vědomi si své nadřazenosti nad ostatními obyvateli lesa a zodpovědnosti k nim. Modlí se velmi často. Svoji bohyni uctívají čas od času oběťmi, za určitých velmi závažných okolností i zvířecími nebo lidskými (pokud je les rozzloben, v případě prosby k bohyni o závažnou věc…). Z vyznavačů se pak rekrutují kněží - driudi. Druid stojí v čele každého společenství a velice často také žijí zcela osamoceně v nejhlubších hvozdech ponořeni do svých motliteb a meditací, dlouhé týdny a měsíce odříznuti od světa v dokonalé harmonii se svým okolím. Zcela zavrhují přenos vědomostí písemnou cestou. Rozmlouvají s hvozdem, rozumí řeči tvorů a rostlin i jejich životním pochodům, často až ztrácejí schopnost komunikovat s lidmi. Les chrání životem. Dojde-li druid osvícení, stane se z něj "pán lesa". Tak prakticky přestávají existovat ve své původní fyzické i duševní podobě, jejich mysl se zcela propojí s duší hvozdu a oni ho ovládají (a les ovládá je). Je-li zabit pán lesa, což není vůbec jednoduché, les velice truchlí, někdy i zemře. Je-li výrazně ublíženo hvozdu, zemře pán. Les svého prána téměř bezmezně chrání. Kněží mohou být velmi mocní.
</p><p>
<strong>Ochránci přírody</strong>: Jejich život je také velmi úzce spjat s přírodou a tím i s Natürwannou, nejsou však tak ortodoxní, jako Druidi lesů. I oni lesy a přírodu vůbec milují a ctí a snaží se žít tak, aby jim jejich, podle nich bezmezně dobrotivá, bohyně věnovala svojí lásku a péči. Většinou jde o lovce, často žijí i v méně přístupných oblastech venkova (hory, pustiny…), zastoupeni jsou asi 8%. Příroda je zcela živí, proto jí projevují vděk motlitbami i slavnostmi (ostavují hlavně příchod jara, zrání a sklizeň, jejich veselé reje a setkání jsou známy i ostatním vyznavačům Natürwanny, většinou se jich účastní i Vyznavači přízně). Ochránci přírody bývají velice přátelští a pohostinní, ochotně se starají o hosty i zbloudilé poutníky. Většinou obchodují s nejbližším městem, týká se to hlavně kožešin a zpět pak nástrojů a zbraní. Duchovními vůdci bývají přátelští a mírně podivínští kněží žijící ve vsích i lesích; pečlivě se starají o svá svatá místa, malé přírodní oltáře v lesích či lukách, které zdobí všerůznými bylinami. Ovládají dobře bylinkářství a léčitelství, dokáží dokonale využít každou rostlinu a její účinky. Kněží mohou být mocní.
</p><p>
<strong>Vyznavači přízně</strong>: Jde hlavně o obyvatele venkova, ale najdeme je dnes vlivem přistěhovalectví i ve městech. Většinou to jsou zemědělci. Modlí se za dobrou sklizeň a dary přírody (mezi ně řadí také pivo, kterému velmi rádi holdují jako svatému daru Natürvanny). Také oni pořádají slavnosti na oslavu Přírody, slavnost jara, zrání a sklizně. Víra však zdaleka tolik neprostupuje jejich životy jako u Druidů a Ochránců, jde spíše o vyjádření spříznění s půdou, kterou užívají a závislosti na ní. V souvislosti s tímto způsobem života a víry můžeme mluvit o minimálně 25% lidí i ostatních ras (hobiti…). Vyznavači přízně mají velice málo kněžích, ti se pak většinu času modlí za úrodu a mírnou zimu, světsky se starají o pořádání slavností. Kněží prakticky nemají moc.
</p>
<h3>Vyznavači Haemera, boha boje</h3>
<p>Dělíme je na dvě větve podle postoje k životu a boji:
</p><p>
<strong>Cesta pokory a práva</strong>: Haemera vyznávají hlavně vojáci a bojovníci. Žádají ho ve svých motlitbách o sílu k ochraně práva, dobra a svých blízkých. Snaží se konat dobro a jednat čestně. Prosí také za své životy, jež velmi často nasazují v boji. Věří, že pokud povedou dobrý život v pravdě a pokoře, dostane se jim odměny od boha. K Haemerovi na Cestě pokory a práva se obrací hlavně lidé, trpaslíci a někdy i elfové, celkem tak 8%. Někdy o jeho přízeň prosí i celé národy, zvláště pak ve válce, kdy jeho uctívačů rapidně přibývá. Víceméně však pro toto náboženství není nejdůležitější část víry, ale spíše životní filozofie jeho vyznavačů. Kněžími bývají bojovníci, kteří se ve své církvi zavážou k šíření dobra cestou meče až do své smrtit, ti pak odcházejí od rodin, stávají se důstojníky i potulnými bojovníky. Kněží mohou být mocní.
</p><p>
<strong>Cesta krve</strong>: Její principy a filozofie je na hony vzdálena od cesty pokory a práva. Bývají to zabijáci bez slitování, nejostřílenější veteráni krvavých válek a masakrů i mladíci cvičení jen k násilnému ukončování lidských životů. Většinou jsou poznamenáni válkou a krví, jíž viděli za svůj život až příliš mnoho. Necítí strach ze smrti a proslýchá se, že dokáží ovládat bolest a některé své tělesné funkce. Tvoří jádra armád, nebo žijí žoldáckým životem. Někdy zabíjí i pro zábavu a z radosti z násilí. Nejsou ostatními příliš oblíbení, jde jen asi o 5% všech ras. Jejich pouto s Haemerem vede přes kněží, kteří většinou cvičí zabijáky a bojovníky speciálních federativních jednotek. Opět jde tedy více o styl života, než přímo víru. Kněží mohou být mocní.
</p>
<h3>Vyznavači Saluse, boha věcí lidských</h3>
<p>Salus je poměrně dost oblíben tam, kde žijí lidé v poměrném blahobytu a prosperitě, zvláště pak ve městech. Vyznavači jsou dvojí a jejich náhled na víru i svět jsou velice silně odlišné.
</p><p>
<strong>Kult peněz</strong>: Vyznává asi 4% obyvatel, tíhnou k němu nejvíce bohatí měšťané. Dá se říci, že zde jde už téměř výhradně o filozofický směr, který se již velice dávno odpojil od přímého uctívání boha a obrátil se bezvýhradně na člověka. Tento kult postrádá kněží. Filozofií příslušníků je snaha o získání a nashromáždění co největšího majetku, skrze což hledají štěstí. Bývají to přísní a odměření lidé, uzavření, ale velice pilní a pracovití a samozřejmě velmi lakomí. Kněží této víry nejsou.
</p><p>
<strong>Kult těla</strong>: Vyznavači tohoto kultu jsou velmi odlišní od Kultu peněz. Bývají celkem pobožní, rádi a často se účastní bohoslužeb (trochu zvláštní formy). Za božské považují všechny příjemné pocity a slasti, jež život nabízí, nejvíce však holdují sexu. S tímto svázali i svoji životní filozofii. Teď více k již zmíněným bohoslužbám kultu: ostatní lidé pro ně nemívají mnoho pochopení, přijdou jim při nejmenším podivínské a pobuřující, mnohdy až nemravné i nechutné. (Ehm, a to znají jen ty veřejné…) Většinou se při nich kultisté věnují drobným hrám (příslušného zaměření) pod vedením kněze. Za osvícené považují členové kultu po fyzické stránce krásné jedince, z nich se také častěji rekrutují kněží, kteří nemají na práci o mnoho více, než sloužit Salusovi. Často bývají vzdělaní a přísluší jim slušné společenské postavení. Dosahují několika stupňů zasvěcení, většinou podle délky kněžské dráhy a od toho se odvíjejícího počtu vykonaných veřejných a také tajných bohoslužeb. Zástupce nalezneme mezi všemi rasami a tvoří asi 8%. Tito požitkářští lidé jsou jinak milí a přívětiví. Kult je velmi starý a v historii často střídal období velké popularity s časy zákazu. V létech rozkvětu vznikla i rozsáhlá náboženská literatura tohoto kultu… Kněží mohou být mocní.
</p>
<h3>Uctívači bohů rodiny</h3>
<p>Vyznavači rodiny nemají přímo jednotného boha, pod tuto víru shrnujeme 2 cesty, jedna z nich má jedinou ústřední bohyni a druhá je přežitkem starých uspořádání víry primitivních národů a ras s životní filozofií troch vzdálenější momentálně běžným lidským filozofickým směrům.
</p><p>
<strong>Kult bohyně matky Ater</strong>: Modlí se k bohyni Matce Ater a v největší úctě drží své matky a ostatní ženské předky. Rodina a její svazek je pro ně posvátný. Žijí často pospolitě ve velkých rozvětvených rodinách několika generací. Největším bohatstvím pro ně jsou zdravé a šťastné děti, kterých mívají hojně. Jde o z přesvědčení nekonfliktní, pracovité lidi. Věří, že jejich cesta životem jim byla předurčena již při narození a sami ji mohou ovlivňovat jen velice málo. Toto náboženství je běžné ve městech i na venkově, nemá však velké zastoupení, jen asi kolem 5%. Lidé vychovaní v této víře uznávají bez problémů existenci jakýchkoli jiných bohů a mladí často přestupují k jiným filozoficko - náboženským směrům, zásadně však k těm umírněným a ctícím základní principy víry v Ater. Kněží této víry nejsou.
</p><p>
<strong>Kult duší otců</strong>: Jak již napovídá název, své prosby a motlitby kultisté směřují k duším svých mužských předků, otců a dědů. Nemají jednoho boha. Pokrevní příbuznost mají v nejvyšší úctě, bratrství považují za svazek překonávající vše včetně smrti. Toto náboženství je velice staré a dnes se k němu hlásí již velice málo vyznavačů, většinou tradicionalističtí trpaslíci a občas lidé, spíše však barbarských národů mimo civilizované země, odhadem kolem 1% a zvolna vymírají. Kněží této víry nejsou.
</p>
<h3>Vyznavači Sciollose, boha učenosti a moudrosti</h3>
<p>Víra ve Sciollose je opět velmi rozšířená. Mezi vyznavači tohoto boha nalézáme zástupce prakticky všech ras. Většinou se jedná spíše o městské obyvatelstvo, ale mohou být i výjimky. Sciollovci podporují vzdělanost, vedou školy… Téměř všichni učenci a vědci náleží k tomuto náboženství. Má 2 základní filozofické větve a dá se říci, že ze všech náboženství je nejotevřenější vzniku těch nových.
</p><p>
<strong>Cesta moudrosti</strong>: První a nejrozšířenější větev vyznavačů Sciollose je právě Cesta moudrosti. Je nejstarší, ač prošla největším počtem reformací a rozporů i dělení. Hlásí se k ní asi kolem 16% obyvatelstva. Cestu moudrosti následují učenci, umělci a vědci, mnohdy i obyčejní lidé. Vyznavači hledají osvícení ve vědomostech a znalostech. Jejich filozofie je na rozdíl od mnoha jiných náboženství velmi úzce spojena s bohem, často tráví mnoho času v rozjímání a motlitbách. Z přesvědčení bývají většinou dobří, celý život hledají nejvyšší moudrost a své vědomosti se snaží (nebo tedy měli by podle regulí církve) využít pro dobro ostatních. Dalším znakem osvícenost této církve je skutečnost, že šíří vzdělání mezi nejširší vrstvy. Cesta moudrosti má mnoho kněží, bývají to učitelé filozofie a teologie či přímo kněží z povolání. Bohoslužby slouží sice zřídka, ale pečlivě se starají o své svěřence ve víře, pečují o jejich duševní rozvoj a pomáhají jim držet se Cesty. Hierarchie kněžstva je sestavena podle schopností a let odpracovaných ve službě víře. Vyznavači Cesty moudrosti bývají velice tolerantní, jediné sváry snad mají s ostatními vyznavači Sciollose, protože jsou velice pevně přesvědčeni, že jen a pouze oni následují pravou víru a, popravdě, Kult čisté pravdy se v lecčems odlišuje od Cesty moudrosti. Už v základních myšlenkách výkladu své víry se diametrálně liší. Kněží mohou být mocní.
</p><p>
<strong>Kult čisté pravdy</strong>: Přívrženců tohoto kultu je o poznání méně, než následovníků Cesty moudrosti, asi kolem 3-4%. Sem náleží téměř výhradně vzdělanci; lidské a občas i jiných ras. Na první pohled nejsou odlišitelní od vyznavačů cesty moudrosti, vystupují velice podobně, jejich filozofie se však diametrálně odlišuje. Nehledají už osvícení jen v moudrosti a dobru, snaží se dosáhnout co nejvyšších vědomostí jakýmkoli způsobem. Jejich svědomí jim nebrání zkoumat i pro Cestu téměř tabuizované směry vědění, nyní se mimo jiné věnují výzkumu zvláštních stavů mysli a jejich projevů (snům, halucinacím, hranicím psychické odolnosti…). Přes to vystupují jako docela normální lidé a mimo svoji víru žijí běžné životy. Kněží tohoto kultu dosahují dvou stupňů zasvěcení, které představuje ani ne tak hranice schopností a vědomostí, ale spíše společenské postavení v církvi. Slouží časté bohoslužby, ty nejvýznamnější může doprovázet lidská oběť. Obřadem zasvěcování se věřící stávají kultisty nižšího svěcení a po určitém čase se mohou dopracovat i do kruhu vyššího svěcení. Kněží vyššího svěcení mají už jedinou povinnost: hledat vhodné adepty k zasvěcení a dále pak hledat Kněze. Knězů je v Kultu čisté pravdy nemnoho, mají nejvyšší moc, slouží všechny důležitější bohoslužby, mají právo obětovat, konat obřad zasvěcení, být nejblíže bohu. Je to většinou prostý věřící se zvláštním nadáním, které mu je podle kultistů propůjčeno bohem. Kněží mohou být mocní.
</p>
<h3>Vyznavači Libartaenny, bohyně svobody</h3>
<p>Toto náboženství nemá příliš silné zastoupení (okolo 3%) a jde opět spíše o filozofický směr či způsob života než o víru. Jeho příslušníci neuznávají autority, šlechtu a moc bohatství, často žijí na hranici zákona. Vychází ze základní myšlenky rovnosti všech narozených tvorů a podle ní se snaží žít (což je jaksi riskantní…). Mnohdy bývají drzí na nevhodných místech, nešetří výsměchem a kritikou společnosti, snad zaslouží přirovnání k anarchistům. Sami tvrdí, že se snaží šířit svobodu. Rasově jsou zastoupeni hlavně lidmi, hobity a občas elfy, často se na tuto víru obrací utiskované a podrobené národy, nepochopení umělci a učenci. Někdy postupují cestou meče, jindy slova nebo žijí v odevzdaném klidu. Libartaenna jim má dodávat sílu a chránit je zla. Kněží této víry nejsou.
</p>
<h3>Vyznavači smrti boha Thanatose</h3>
<p>Vyznavačů Thanatose je nejméně. Jsou zastoupeni mezi všemi rasami a následující dvě církve se opět velice liší.
</p><p>
<strong>Pohřbívající</strong>: Jak již napovídá název, většinou jde o obhospodařovatele hřbitovů či hrobníky. Pečují o poslední věci všech ras a snad právě proto jsou trochu podivínští (avšak potřební a žádaní). Prostí věřící bývají vážní, ale jinak docela průměrní lidé. Kněžími se stává poměrně hodně z nich. Ti se modlí za duše zesnulých a jako jediní je dokáží správně připravit na cestu "na druhou stranu", jinak duším může hrozit věčné bloudění světem či mnohé horší. Najdeme je v každém městě nebo větší vsi, přes to jen asi jako 1% všech obyvatel. Ostatní lidé se jich trochu straní, jejich práce jim přijde podivná a cizí. Kněží mohou být mocní.
</p><p>
<strong>Zabíječi</strong>: Jinak také "ti, kteří převádějí na druhou stranu". Žijí zcela za okrajem společnosti lidské i ostatních (odhadem snad kolem 1%). Mají podivnou, však velice špatnou pověst. Nikdo nebyl schopen říci mi o nich nic bližšího… O knězích nic nevím, podle domněnek však mohou být velmi mocní.
</p>