title = "Stránky LARPu Erinor (pořádané skupinou Pilirion) &ndash; knihovna: O hobitovi, který vyrostl";
keywords = "larp, erinor, fantasy, dřevárny, roleplay, povídka, knihovna, hobit";
description = "Stránky LARPu Erinor, sekce knihovna, O hobitovi, který vyrostl";

Sem lze napsat libovolný komentář, nebude zobrazen. Zobrazí se pouze text pod čarou.
----------
<h1>O hobitovi, který vyrostl</h1>
<p>Za sedmero kopci a devatero řekami tekl malý potůček. A v nejkrásnějším zákrutu potůčku hned pod březovým hájem se rozkládala malá víska. Z komínů stoupal hustý kouř a krajem se nesla vůně čerstvého chleba. V té vesničce žili malí lidičkové se zakulacenými bříšky, veselí a přívětiví. A mezi nimi, nerozpoznatelný od jiných půlčíků, vyrůstal i Čepek Dlouhoprst.
</p><p>Čepek byl chlapec menšího vzrůstu s tmavými vlasy nakrátko střiženými a pronikavým pohledem. Už odmala však byl neposedný a plný nezkrotné touhy po dobrodružství. Jeho maminka ho přísně napomínala, ať vypustí z hlavy všechny ty nesmysly o obrech, dracích a pokladech, ale on na její příkazy pranic nedbal a toulal se po okolí dál než bylo pro tak malého hobita zdrávo.
</p><p>Jednoho dne se malý Čepek zatoulal až do dalekých a temných lesů na západní straně údolí. Poskakoval si v rytmu veselé písničky a nedával pozor na cestu, která se před ním vinula. Pěšinka se postupně zužovala, a jak den pomalu uhasínal, tak se kolem malého hobita rozprostřel neproniknutelný závoj temnoty. A Čepek se začal bát! Šouravým krokem tápal v okolní tmě a slzy měl na krajíčku. "Kéž bych jen byl poslouchal maminku!", říkal si, když tu náhle zahlédl malé světýlko. Záře ho dovedla až na malou mýtinku, osvětlenou mnoha loučemi. Tráva byla zbarvená rudě a vybledlé kosti ležely rozházené pod kmeny stromů. A vprostřed ní stál malý dřevěný stolek plný jídla! Byly tam ty nejsladší a nejšťavnatější pochutiny, jaké kdy Čepek spatřil! "To přeci nemůže být tak zlé místo, když je tu tolik dobrot" řekl si. A protože už byl notně hladový, tak se pustil bez váhání do jídla.
</p><p>A jak tak hltal všechny ty dobroty, tak si nevšiml vysokého muže, který vstoupil do světla pochodní. Byl ustrojen v dlouhém splývavém šatu tmavých barev a oči mu plály zlobou. "Jaký mrzký tvor se opovážil znesvětit svaté místo naší nejvznešenější bohyně?" zahřímal, "teď draze zaplatíš za svou drzost. Tato urážka nezůstane bez trestu!" To už Čepek na nic nečekal a pádil lesem pryč, co mu nohy stačily. Utíkal tak dlouho, až se dostal k okraji své rodné vesnice. Vběhl všecek zadýchaný na náměstí a uviděl svou maminku, jak pro něho pláče na zahrádce jejich domku. "Maminko, maminko, už neplač. Už jsem zpátky, tvůj Čepek se ti vrátil!" Ale ona vzhlédla uplakanýma očima a odpověděla: "Ty nejsi můj Čepek. Můj synek byl malého vzrůstu, jasných očí a veselé povahy. Ty nejsi můj syn." A Čepek pohlédl do průzračné vody bublajícího potůčku a spatřil sám sebe na dva metry vysokého. Už nebyl onen malý hobitek, ale velký obr. Přesně takový, jakého vídal ve svých dobrodružných představách. Ulekl se toho obrazu a dal se na útěk. Osamocen pak cestoval krajem, vědom si toho, že se ke své mamince takhle vrátit nemůže.
</p><p>Jeho život se stal vlnou smutku a beznaděje. Den za dnem utíkaly a jediné, co ho drželo při životě, byla touha po domovu. Přešel rok a on seděl na rozcestí zahleděn do svých myšlenek natolik, že nepostřehl poutníka blížícího se po prašné cestě. "Kdopak to tu sedí jako tělo bez duše?" otázal se a zpod bílých vousů pronikl k půlčíkovi vlídný úsměv. "Jsem Čepek Dlouhoprst" odpověděl slušně hobit, "cestuji sám a sním o domově, který jsem navždy ztratil svou nerozvážností. Teď lituji, že jsem nebyl poslušný svých rodičů, a odpykávám trest, který mi byl vyměřen." "Trest říkáš?" otázal se stařeček, "hm, vidím ti v očích, jak moc lituješ své nerozvážnosti. Už jsi pykal dost dlouho." Běž domů a nemeškej, tvá maminka tě jistě přijme s otevřenou náručí.
</p><p>"Když Čepek opět vzhlédl k podivnému muži, spatřil místo něj jen zelenou ratolest snášející se k zemi v místě, kde stál. Rychle ji zdvihl, vložil za klopu své vesty a rozběhl se směrem k domovu. Když vběhl do domku svých rodičů a skočil mamince do náruče, už byl opět malý hobitek jako dřív.
</p>