title = "Stránky LARPu Erinor (pořádané skupinou Pilirion) &ndash; knihovna: Otevřená náruč";
keywords = "larp, erinor, fantasy, dřevárny, roleplay, povídka, knihovna, otevřená, náruč";
description = "Stránky LARPu Erinor, sekce knihovna, povídka Otevřená náruč";

Sem lze napsat libovolný komentář, nebude zobrazen. Zobrazí se pouze text pod čarou.
----------
<h1>Otevřená náruč</h1>
<p>"Posaďte se přátelé. Dnes jsem se rozhodl s vámi popřemýšlet o tom jaké vzpomínky si sebou nesete a co si z nich odnést. Vyšel jsem dnes ráno ven s tím, že si půjdu pro příděl na snídani. Mé boty se každým krokem zakusovali do vrstvy čerstvého sněhu, po kterém ten den ještě nikdo nešel. Ten zvuk mám moc rád. Až v jednu chvíli sníh nechřoupnul. Ve sněhu na zemi se válel pergamen. Přečetl jsem si ho a teď ho přečtu vám. Nechci vám obnovit špatné vzpomínky, jen poslouchejte o čem ten vzdělaný muž přemýšlel. Pak si o tom ještě pohovoříme.
</p><br>
<p>Marný, bloudivý pohled prohlížel cestu. Tak jako ty ostatní dlouhé míle před tím se vinula po úbočí a rozvláčně klesala do údolí. Ve předu byly vidět další skupinky jdoucí toutéž cestou a za stejným cílem jak se pomalu ztrácí v mlze. Do dálky se nesl zvuk nohou brodících se vrstvami bahna a vrzání kol vozů.
</p><p>Nikdo nemluvil. Nebylo již slyšet ani nadávky ani žal. Každá noha tupě opakovala pohyb té před ní. Rozhlédl-li se někdo spatřil oči zkroušené a mysl pohrouženou do sebe. Raději se dál nerozhlížel.
</p><p>V dálce zaševelili listy stromů. List staré osiky se prudce ohnul, div se neodlomil jakou silou do něj udeřila kapka. Najednou už bylo slyšel šumění půlky stromu. Všem do dálky ten starý strom oznamoval, kde už prší. Všichni se pomalu zastavili. Čekali. Výmoly se začali plnit. Malé loužičky se spojovali do louží, z kterých pak odtékal proud dolů. Čekali. Začalo být slyšet hučení. Země pod nohama se změnila během chvíle ve dravou řeku. Nebylo možné pokračovat. Tak silný déšť ještě nezažili. Cesta se stala nebezpečnou.
</p><p>Žluté, ohnivé jazýčky sálající teplo nesly poselství naděje. Pak přišel spánek a pro dnešní den vysvobození.
</p><p>Ráno se přihlásili jako obvykle o své slovo dravé sluneční paprsky. Nedovolili nikomu dospat. Však každý se ujistil pohledem do údolí a cosi zavrčel pod fousy.
</p><p>Zdola se valila hustá mlha a jak pára nad hrncem stoupala výš. Přišla velmi rychle. Stěna bílé nicoty pohltila vše a všechny, než se stačili v ranních paprscích ohřát. Bylo to jako by vám někdo na rozpálené tváře od kamen plácl studený, mokrý a namrzlý hadr.
</p><p>Celé to začalo znovu. Nikdo nemluvil, stálo by to příliž energie. Zas začala skřípat kola. Všude se rozléhal zvuk jako když hodíte velký kámen do louže plné bahna. Panovala ale ponurejší nálada než včera. Všechny děti, které cestu předtím šli poslali spát do vozů. Každý sice věděl, že koně budou ještě vyčerpanější, ale nic nenamítal. Tohle pro ně nebyl pohled. Bouře byla opravdu silná. Vyšlapaným úvozem cesty se prohnal proud bahna, který bral všechno co se neubránilo jeho síle. Nahoře, výš byla cesta ještě strmější. Někteří neměli to štěstí. Kousky látek teď zakrývali jejich osud. Nikdo je nepohřbíval. Ani kněží. Všichni se báli smrti, která teď byla přímo pod jejich šlépějemi. Ta skutečná se, ale blížila každou hodinou.
</p><p>Bílá mlha rozsvícená ze shora sluncem bodala do očí. Na větvičce smrku se vytvořila první jehlička ledu. Najednou jich byly tisíce. Každý předmět pokryla vrstvička tenoučkých čirých jehliček. Byly jak z křišťálu. Všichni rázem věděli na co se dívat a rádi zapomněli kudy jdou. Věděli, ale že z té nádhery čiší obavy, které měli. Věděli, že z ní čiší smrt. Přišla zima.
</p><br>
<p>Mlha zhoustla a byl z ní cítit kouř. Za krátko už slunce zajde za obzor, ale pokračujeme v cestě. Naděje brzkého konce je silnější. Městečko Poddvorov prozrazovaly již světla. V myšlenkách přemítáme. Každý přemýšlí nad dalším krokem. Svádí svůj souboj únava a odhodlání. Vůle ale vyhrála.
</p><p>"Hej kapitáne sú tu další". V každém z nás hrklo. Z temnoty vystoupila postava s vojenským tabardem.
</p><br>
<p>Přivítání toho večera nebylo příjemné. Přiběhli sloužící z dozoru a odvedli nás do tábora. Každý muž dostal 1 deku, ženy 2 a ty s dětmi 4. Byl to takový hadřík, člověk by do toho ani nohy nezabalil. Pak nám přidělili stan a dali nás spát. Naše věci procházeli kontrolou. I kdejaký zločinec na tom byl lépe než mi v tu chvíli.
</p><p>Tyto zápisky píši s více než týdenním zpožděním. Sebrali mi věci a mezi nimi i brk. Vzpomínky již nejsou tak živé. Hlavní věcí je že jsme přežili což je dobře. Hůř být nemůže. Den po nás dorazili ještě další. Nikdo po nich ale už nepřišel. Napadl sníh a přikryl svou bílou nevinnou tváří únavu, strach i odhodlání. Buď jim Thanatos všem milostiv.
</p><p>Ráno nám řekli co se děje a proč jsme tady. V Zaluži se prý stal nějaký problém a bylo nařízeno, že každý kdo odtamtud přišel musí projít prohlídkou. Strážní jak se jim tu říká jsou prý z federace a přibrali k sobě několik místních dobrovolníků. Platí zde táborová pravidla. I kněží se musejí podřídit.
</p><p>A proč tu vlastně jsme tak dlouho? A proč v soldátském táboře. Mnozí se domnívají, ale nic ve skutečnosti neví. Mysleli jsme, že každý si sežene glejt a můžeme jít. Realita je jiná. Drží nás tu už podezřele dlouho na to, aby jen vyřizovali dokumenty.
</p><p>Tři chlapíci se pokusili utéct. Chytli je. Prohledali znovu jejich věci a našli spoustu zlata. Byli odsouzeni na pranýř. Všichni se na to museli dívat. Čtvrt dne tam byli jen v košilích. Druhý den měli všichni zápal plic a pak už o nich nikdo neví. Prý je poslali k felčarovi, ale kdo ví.
</p><br>
<p>Dneska nám řekli proč tu jsme. Z oblohy se snášel drobounký déšť a strhával sebou vločky. Břízy kolem tábora byly skloněné pod tíhou našich myšlenek. Byly znamením, náladou celého dne. Pokud nebyly obtěžkány ledem, tak že se jejich koruny blížili k zemi bylo dobře. Stékal-li z jejich kmenů pramínek vody, tekli slzy i těm nejtvrdším chlapům.
</p><p>Prý chrání městečko Poddvorov před hladomorem a místní kraj před povstáním. Zkrátka přišlo nás moc a ještě je tu soldie. Tak zřídili tábory, v kterých máme přežít až do jara. Poslední dobou zde nouze opravdu není. Jídlo i voda jsou, všichni mají příděl. Musí se ale odpracovat. A ten kdo nic neumí se povinně vyučuje k řemeslu.
</p><p>Dnes večer jsem vyšel ze srubu a přemýšlím. Chtěl bych ještě mnoho napsat, ale dochází mi tuž. Jinou asi neseženu, leda si ji vypůjčit od úředníků. Zmrzlé bláto prokřupává pod mími kroky. Břízy s jejich namrzlými větvičkami mi zpívají s větrem jemnou zvonkohru. Je ticho. Proč já tyhle řádky vlastně píšu? Snad na jejich památku.
</p>