title = "Stránky LARPu Erinor (pořádané skupinou Pilirion) &ndash; svět: mapa Lithénu";
keywords = "larp, erinor, fantasy, dřevárny, roleplay, svět, mapa, Lithén";
description = "Stránky LARPu Erinor, sekce svět, mapa Lithénu";

Sem lze napsat libovolný komentář, nebude zobrazen. Zobrazí se pouze text pod čarou.
----------
<h1>Mapa Lithénu a přilehlých oblastí</h1>

<p>Názvy oblastí uvedené na mapě nejsou většinou jména dnešních států a příliš nevypovídají o jejich hranicích. Jde jen o názvy tradičních oblastí. Ve většině oblastí dnes najdete několik menších států jejichž hranice se velice často posouvají a mění. Proto nemá příliš cenu je zakreslovat.
</p><a href="img/mapy/lithen.jpg"><img src="img/mapy/thumb/lithen.jpg" class="fl"></a><p>Lithénská federace se rozkládá na rozlehlém území zasahujícím na jihu až do subtropických oblastí na hranici Ragadornu s národy pouštních elfů. Radagornské podnebí je dosti teplé a vlhké přímořské oblasti jsou proto velmi úrodné. Většina federace se pak rozkládá v pásu mírném až na severu pod horami Ugalu (jinak zvané Severní hory) a v okolí řeky Ogdy přechází do subpolárních chladných oblastí. Za Ogdou, a tedy i za hranicí federace najdete už jen suchou tundru. Na východě omývá břehy států oceán. Odtud také přichází většina srážek. Západní Krhavé hory se táhnou po celé hranici federace. Směrem k jihu stoupají strmé štíty až do výšek přes 4000 metrů. Zde oddělují mírný Alderah od divokých oblastí snědých pouštních elfů a lidí.
</p><p>Federace ve své rozloze obsahuje samozřejmě několik území obývaných převážně rasami nelidskými. tyto menšiny obývají často svá tradiční území kde můžete najít centra jejich kultury i moci. Na severu v Irotu při řece Ogdě, zvláště pak poblíž jejích ústí se nachází pláně tradičně obývané barbary. Polární elfové žijí hlavně na Nolgistských pláních mezi jezery a zamrzajícími bažinami i v podhůří Ugalu. Domovem elfů z plání je dnes pohoří nedaleko Lithénu. Dříve žili na úrodných pláních pod horami, ale rozmáhající se lidé je vytlačili na horské louky a do lesů. Pouštní elfy, jak už bylo zmíněno, najdeme na jihu Ragadornu, v Černé poušti i za elfími horami daleko za hranicí Lithénu. Trpaslíci dnes už žijí na mnoha místech, ale jejich původ nacházíme v severní cípu Krhavých hor u pramenů řeky Skelefteären. Hobiti jsou pak doma všude ve federaci. Jejich původ není znám. Bez problémů žijí v lidských městech a se svými většími sousedy dobře vychází.
</p><p>Na závěr se ještě budu v tomto popise věnovat jazykům místních názvů. Na úplném jihu na Ragadornské hranici a za ní směrem do pouště můžeme najít obce s názvy v jazycích podobných našim románským a také v tradiční elfštině. Dále na sever v Ragadornu a v Dargethském Středozemí jsou názvy v jazycích germánských podobných zvláště naší Němčině. V Albirey pak názvy západní germánštiny, anglosaské. Alderah užívá jména západoslovanská, sever zvláště polská, avšak nová oblast Zaluže je poněkud zaostalejší s domorodým jazykem podobným Ruštině. Mezihorské názvy se pak silně odlišují od ostatních netradičním ugrofinským jazykem a přecházejí na Nolgitských pláních v severogermánské. Irot je pak opět plný slovanských jmen, tentokrát východních. A zcela oddělený Eir, země skvělých mořeplavců, používá jména nizozemská. 
</p>